<?xml version="1.0" encoding="utf-8"?><Database Name="Movie_FinalDB_Project" Class="MovieTheatreDataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\Movie_FinalDB_Project.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="FinalOOP2Project.Properties.Settings" SettingsPropertyName="Movie_FinalDB_ProjectConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="UserId" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Manager" Member="Managers">
    <Type Name="Manager">
      <Column Name="ManagerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ManagerUsername" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ManagerPassword" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movies" Member="Movies">
    <Type Name="Movies">
      <Column Name="MovieId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MovieName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Genre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfRelease" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Actors" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Movies_ScreenRoom" Member="ScreenRooms" ThisKey="MovieId" OtherKey="MovieId" Type="ScreenRoom" />
    </Type>
  </Table>
  <Table Name="dbo.ScreenRoom" Member="ScreenRooms">
    <Type Name="ScreenRoom">
      <Column Name="ScreenRoomId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovieId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalSeatNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ScreenRoom_ShowTime" Member="ShowTimes" ThisKey="ScreenRoomId" OtherKey="ScreenRoomId" Type="ShowTime" />
      <Association Name="Movies_ScreenRoom" Member="Movies" Storage="_Movie" ThisKey="MovieId" OtherKey="MovieId" Type="Movies" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ticket" Member="Tickets">
    <Type Name="Ticket">
      <Column Name="ticketId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="E_ticket" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="availability" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Ticket_MovieTicketUser" Member="MovieTicketUsers" ThisKey="ticketId" OtherKey="TicketId" Type="MovieTicketUser" />
    </Type>
  </Table>
  <Table Name="dbo.MovieTicketUser" Member="MovieTicketUsers">
    <Type Name="MovieTicketUser">
      <Column Name="MovieId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TicketId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Ticket_MovieTicketUser" Member="Ticket" ThisKey="TicketId" OtherKey="ticketId" Type="Ticket" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShowTime" Member="ShowTimes">
    <Type Name="ShowTime">
      <Column Name="ShowTimeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MovieId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ScreenRoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ScreenRoom_ShowTime" Member="ScreenRoom" ThisKey="ScreenRoomId" OtherKey="ScreenRoomId" Type="ScreenRoom" IsForeignKey="true" />
    </Type>
  </Table>
</Database>